"""
Django settings for sre_console project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file if present so ARNs and other
# environment-specific settings are not committed to source control.
env_path = BASE_DIR / ".env"
if env_path.exists():
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            # .env values take precedence over any existing environment variables.
            os.environ[key] = value

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=l8s*@bo#@12x8+3g)8#9m#_2i$lha_2!mqi=@hsu2g9-)inl&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'landing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sre_console.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'landing.context_processors.quick_operations',
            ],
        },
    },
]

WSGI_APPLICATION = 'sre_console.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication (Cognito integration deferred to a later feature)
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Backend: mock (default) or real Lambda/Step Functions. Set USE_MOCK_BACKEND = False
# and configure AWS ARNs below (via environment variables or .env) to use the real backend.
USE_MOCK_BACKEND = False
# Stack name passed to query Lambda (e.g. list-pipeline-executions) so it knows which stack to use.
SRE_STACK_NAME = os.getenv("SRE_STACK_NAME", "sre-management")
# ARNs for real backend (required when USE_MOCK_BACKEND is False). These should be provided
# via environment variables or a local .env file that is not committed to source control.
SRE_MANAGEMENT_FUNCTION_ARN = os.getenv("SRE_MANAGEMENT_FUNCTION_ARN")
SRE_QUERY_FUNCTION_ARN = os.getenv("SRE_QUERY_FUNCTION_ARN")
PROVISION_AD_CONNECTOR_STATE_MACHINE_ARN = os.getenv("PROVISION_AD_CONNECTOR_STATE_MACHINE_ARN")
PROVISION_WORKSPACE_STATE_MACHINE_ARN = os.getenv("PROVISION_WORKSPACE_STATE_MACHINE_ARN")
PROVISION_WINDOWS_WORKSPACE_STATE_MACHINE_ARN = os.getenv("PROVISION_WINDOWS_WORKSPACE_STATE_MACHINE_ARN")
PROVISION_EC2_INSTANCE_STATE_MACHINE_ARN = os.getenv("PROVISION_EC2_INSTANCE_STATE_MACHINE_ARN")

# Landing page: pipeline activity table refresh interval (seconds). Set to 0 to disable polling.
LANDING_PIPELINE_POLL_INTERVAL_SECONDS = 60

# Logging: show INFO from landing and real backend so pipeline-executions API is debuggable in console.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "landing": {"level": "INFO", "handlers": ["console"]},
        "landing.backend": {"level": "INFO", "handlers": ["console"]},
    },
}
